// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (customer_id, product_id, currency, status, ledger_account_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, customer_id, product_id, currency, status, ledger_account_id, created_at, updated_at
`

type CreateAccountParams struct {
	CustomerID      pgtype.UUID
	ProductID       pgtype.UUID
	Currency        string
	Status          string
	LedgerAccountID pgtype.UUID
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.CustomerID,
		arg.ProductID,
		arg.Currency,
		arg.Status,
		arg.LedgerAccountID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ProductID,
		&i.Currency,
		&i.Status,
		&i.LedgerAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLedgerAccount = `-- name: CreateLedgerAccount :one
INSERT INTO chart_of_accounts (code, name, type, currency)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateLedgerAccountParams struct {
	Code     string
	Name     string
	Type     string
	Currency string
}

func (q *Queries) CreateLedgerAccount(ctx context.Context, arg CreateLedgerAccountParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createLedgerAccount,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.Currency,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, customer_id, product_id, currency, status, ledger_account_id, created_at, updated_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ProductID,
		&i.Currency,
		&i.Status,
		&i.LedgerAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByCode = `-- name: GetProductByCode :one
SELECT id, code, currency FROM product WHERE code = $1
`

type GetProductByCodeRow struct {
	ID       pgtype.UUID
	Code     string
	Currency string
}

func (q *Queries) GetProductByCode(ctx context.Context, code string) (GetProductByCodeRow, error) {
	row := q.db.QueryRow(ctx, getProductByCode, code)
	var i GetProductByCodeRow
	err := row.Scan(&i.ID, &i.Code, &i.Currency)
	return i, err
}

const listAccountsByCustomer = `-- name: ListAccountsByCustomer :many
SELECT id, customer_id, product_id, currency, status, ledger_account_id, created_at, updated_at FROM accounts WHERE customer_id = $1 ORDER BY created_at
`

func (q *Queries) ListAccountsByCustomer(ctx context.Context, customerID pgtype.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.ProductID,
			&i.Currency,
			&i.Status,
			&i.LedgerAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountStatus = `-- name: UpdateAccountStatus :exec
UPDATE accounts SET status = $2, updated_at = now() WHERE id = $1
`

type UpdateAccountStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) error {
	_, err := q.db.Exec(ctx, updateAccountStatus, arg.ID, arg.Status)
	return err
}
