// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCredential = `-- name: CreateCredential :exec
INSERT INTO credentials (customer_id, password_hash)
VALUES ($1, $2)
`

type CreateCredentialParams struct {
	CustomerID   pgtype.UUID
	PasswordHash string
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.Exec(ctx, createCredential, arg.CustomerID, arg.PasswordHash)
	return err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (name, email)
VALUES ($1, $2)
RETURNING id, name, email, phone, status, kyc_status, created_at, updated_at
`

type CreateCustomerParams struct {
	Name  string
	Email string
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer, arg.Name, arg.Email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.KycStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialByEmail = `-- name: GetCredentialByEmail :one
SELECT c.id, cr.password_hash
FROM customers c
JOIN credentials cr ON cr.customer_id = c.id
WHERE c.email = $1
`

type GetCredentialByEmailRow struct {
	ID           pgtype.UUID
	PasswordHash string
}

func (q *Queries) GetCredentialByEmail(ctx context.Context, email string) (GetCredentialByEmailRow, error) {
	row := q.db.QueryRow(ctx, getCredentialByEmail, email)
	var i GetCredentialByEmailRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT id, name, email, phone, status, kyc_status, created_at, updated_at FROM customers WHERE email = $1
`

func (q *Queries) GetCustomerByEmail(ctx context.Context, email string) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByEmail, email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.KycStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, name, email, phone, status, kyc_status, created_at, updated_at FROM customers WHERE id = $1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id pgtype.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Status,
		&i.KycStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
