// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deposit.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, customer_id, product_id, currency, status, ledger_account_id
FROM accounts WHERE id = $1 FOR UPDATE
`

type GetAccountForUpdateRow struct {
	ID              pgtype.UUID
	CustomerID      pgtype.UUID
	ProductID       pgtype.UUID
	Currency        string
	Status          string
	LedgerAccountID pgtype.UUID
}

func (q *Queries) GetAccountForUpdate(ctx context.Context, id pgtype.UUID) (GetAccountForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i GetAccountForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.ProductID,
		&i.Currency,
		&i.Status,
		&i.LedgerAccountID,
	)
	return i, err
}
