// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEntry = `-- name: GetEntry :one
SELECT id, transaction_type, description, booking_date
FROM journal_entry WHERE id = $1
`

type GetEntryRow struct {
	ID              pgtype.UUID
	TransactionType string
	Description     string
	BookingDate     pgtype.Date
}

func (q *Queries) GetEntry(ctx context.Context, id pgtype.UUID) (GetEntryRow, error) {
	row := q.db.QueryRow(ctx, getEntry, id)
	var i GetEntryRow
	err := row.Scan(
		&i.ID,
		&i.TransactionType,
		&i.Description,
		&i.BookingDate,
	)
	return i, err
}

const listEntriesByAccount = `-- name: ListEntriesByAccount :many
SELECT je.id, je.transaction_type, je.description, je.booking_date, je.created_at
FROM journal_entry je
JOIN journal_line jl ON jl.journal_entry_id = je.id
WHERE jl.ledger_account_id = $1
GROUP BY je.id
ORDER BY je.created_at DESC
LIMIT $2 OFFSET $3
`

type ListEntriesByAccountParams struct {
	LedgerAccountID pgtype.UUID
	Limit           int32
	Offset          int32
}

type ListEntriesByAccountRow struct {
	ID              pgtype.UUID
	TransactionType string
	Description     string
	BookingDate     pgtype.Date
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) ListEntriesByAccount(ctx context.Context, arg ListEntriesByAccountParams) ([]ListEntriesByAccountRow, error) {
	rows, err := q.db.Query(ctx, listEntriesByAccount, arg.LedgerAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesByAccountRow
	for rows.Next() {
		var i ListEntriesByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionType,
			&i.Description,
			&i.BookingDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinesByEntry = `-- name: ListLinesByEntry :many
SELECT ledger_account_id, direction, amount_minor, currency
FROM journal_line
WHERE journal_entry_id = $1
`

type ListLinesByEntryRow struct {
	LedgerAccountID pgtype.UUID
	Direction       string
	AmountMinor     int64
	Currency        string
}

func (q *Queries) ListLinesByEntry(ctx context.Context, journalEntryID pgtype.UUID) ([]ListLinesByEntryRow, error) {
	rows, err := q.db.Query(ctx, listLinesByEntry, journalEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinesByEntryRow
	for rows.Next() {
		var i ListLinesByEntryRow
		if err := rows.Scan(
			&i.LedgerAccountID,
			&i.Direction,
			&i.AmountMinor,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
