// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hold.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHold = `-- name: CreateHold :one
INSERT INTO hold (account_id, amount_minor, currency) VALUES ($1, $2, $3) RETURNING id
`

type CreateHoldParams struct {
	AccountID   pgtype.UUID
	AmountMinor int64
	Currency    string
}

func (q *Queries) CreateHold(ctx context.Context, arg CreateHoldParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createHold, arg.AccountID, arg.AmountMinor, arg.Currency)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const releaseHold = `-- name: ReleaseHold :exec
UPDATE hold SET status = 'released' WHERE id = $1 AND status = 'active'
`

func (q *Queries) ReleaseHold(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, releaseHold, id)
	return err
}

const sumActiveHolds = `-- name: SumActiveHolds :one
SELECT COALESCE(SUM(amount_minor), 0)::bigint FROM hold
WHERE account_id = $1 AND status = 'active'
`

func (q *Queries) SumActiveHolds(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumActiveHolds, accountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
