// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package postgres

import (
	"context"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :exec
INSERT INTO idempotency_key (key, request_hash, response_body, status_code)
VALUES ($1, $2, $3, $4)
`

type CreateIdempotencyKeyParams struct {
	Key          string
	RequestHash  string
	ResponseBody []byte
	StatusCode   int32
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, createIdempotencyKey,
		arg.Key,
		arg.RequestHash,
		arg.ResponseBody,
		arg.StatusCode,
	)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, request_hash, response_body, status_code FROM idempotency_key WHERE key = $1
`

type GetIdempotencyKeyRow struct {
	Key          string
	RequestHash  string
	ResponseBody []byte
	StatusCode   int32
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, key string) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, key)
	var i GetIdempotencyKeyRow
	err := row.Scan(
		&i.Key,
		&i.RequestHash,
		&i.ResponseBody,
		&i.StatusCode,
	)
	return i, err
}
