// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: interest.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccrual = `-- name: CreateAccrual :exec
INSERT INTO interest_accrual (account_id, accrual_date, amount_minor, currency)
VALUES ($1, $2, $3, $4)
`

type CreateAccrualParams struct {
	AccountID   pgtype.UUID
	AccrualDate pgtype.Date
	AmountMinor int64
	Currency    string
}

func (q *Queries) CreateAccrual(ctx context.Context, arg CreateAccrualParams) error {
	_, err := q.db.Exec(ctx, createAccrual,
		arg.AccountID,
		arg.AccrualDate,
		arg.AmountMinor,
		arg.Currency,
	)
	return err
}

const listActiveDepositAccounts = `-- name: ListActiveDepositAccounts :many
SELECT a.id, a.ledger_account_id, a.currency, p.interest_rate_bps
FROM accounts a
JOIN product p ON p.id = a.product_id
WHERE a.status = 'active' AND p.kind = 'deposit'
`

type ListActiveDepositAccountsRow struct {
	ID              pgtype.UUID
	LedgerAccountID pgtype.UUID
	Currency        string
	InterestRateBps int32
}

func (q *Queries) ListActiveDepositAccounts(ctx context.Context) ([]ListActiveDepositAccountsRow, error) {
	rows, err := q.db.Query(ctx, listActiveDepositAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveDepositAccountsRow
	for rows.Next() {
		var i ListActiveDepositAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.LedgerAccountID,
			&i.Currency,
			&i.InterestRateBps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAccrualsCapitalized = `-- name: MarkAccrualsCapitalized :exec
UPDATE interest_accrual SET capitalized = true WHERE account_id = $1 AND capitalized = false
`

func (q *Queries) MarkAccrualsCapitalized(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAccrualsCapitalized, accountID)
	return err
}

const sumUncapitalizedAccruals = `-- name: SumUncapitalizedAccruals :one
SELECT COALESCE(SUM(amount_minor), 0)::bigint
FROM interest_accrual WHERE account_id = $1 AND capitalized = false
`

func (q *Queries) SumUncapitalizedAccruals(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumUncapitalizedAccruals, accountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
