// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJournalEntry = `-- name: CreateJournalEntry :one
INSERT INTO journal_entry (transaction_type, description, booking_date, value_date)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateJournalEntryParams struct {
	TransactionType string
	Description     string
	BookingDate     pgtype.Date
	ValueDate       pgtype.Date
}

func (q *Queries) CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createJournalEntry,
		arg.TransactionType,
		arg.Description,
		arg.BookingDate,
		arg.ValueDate,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createJournalLine = `-- name: CreateJournalLine :exec
INSERT INTO journal_line (journal_entry_id, ledger_account_id, direction, amount_minor, currency)
VALUES ($1, $2, $3, $4, $5)
`

type CreateJournalLineParams struct {
	JournalEntryID  pgtype.UUID
	LedgerAccountID pgtype.UUID
	Direction       string
	AmountMinor     int64
	Currency        string
}

func (q *Queries) CreateJournalLine(ctx context.Context, arg CreateJournalLineParams) error {
	_, err := q.db.Exec(ctx, createJournalLine,
		arg.JournalEntryID,
		arg.LedgerAccountID,
		arg.Direction,
		arg.AmountMinor,
		arg.Currency,
	)
	return err
}

const getAccountByCode = `-- name: GetAccountByCode :one
SELECT id, code, name, type, currency FROM chart_of_accounts WHERE code = $1
`

func (q *Queries) GetAccountByCode(ctx context.Context, code string) (ChartOfAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByCode, code)
	var i ChartOfAccount
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Currency,
	)
	return i, err
}

const ledgerBalance = `-- name: LedgerBalance :one
SELECT COALESCE(SUM(
  CASE WHEN direction = 'credit' THEN amount_minor ELSE -amount_minor END
), 0)::bigint AS balance
FROM journal_line
WHERE ledger_account_id = $1
`

func (q *Queries) LedgerBalance(ctx context.Context, ledgerAccountID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, ledgerBalance, ledgerAccountID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}
