// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: loan.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDueInstallments = `-- name: CountDueInstallments :one
SELECT COUNT(*) FROM loan_installments WHERE loan_id = $1 AND status = 'due'
`

func (q *Queries) CountDueInstallments(ctx context.Context, loanID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDueInstallments, loanID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLoan = `-- name: CreateLoan :one
INSERT INTO loans (customer_id, deposit_account_id, principal_minor, term_months, interest_rate_bps, currency, disbursed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, customer_id, deposit_account_id, principal_minor, term_months, interest_rate_bps, currency, status, disbursed_at, created_at
`

type CreateLoanParams struct {
	CustomerID       pgtype.UUID
	DepositAccountID pgtype.UUID
	PrincipalMinor   int64
	TermMonths       int32
	InterestRateBps  int32
	Currency         string
	DisbursedAt      pgtype.Timestamptz
}

func (q *Queries) CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, createLoan,
		arg.CustomerID,
		arg.DepositAccountID,
		arg.PrincipalMinor,
		arg.TermMonths,
		arg.InterestRateBps,
		arg.Currency,
		arg.DisbursedAt,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.DepositAccountID,
		&i.PrincipalMinor,
		&i.TermMonths,
		&i.InterestRateBps,
		&i.Currency,
		&i.Status,
		&i.DisbursedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createLoanInstallment = `-- name: CreateLoanInstallment :exec
INSERT INTO loan_installments (loan_id, installment_no, due_date, principal_minor, interest_minor, balance_minor)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateLoanInstallmentParams struct {
	LoanID         pgtype.UUID
	InstallmentNo  int32
	DueDate        pgtype.Date
	PrincipalMinor int64
	InterestMinor  int64
	BalanceMinor   int64
}

func (q *Queries) CreateLoanInstallment(ctx context.Context, arg CreateLoanInstallmentParams) error {
	_, err := q.db.Exec(ctx, createLoanInstallment,
		arg.LoanID,
		arg.InstallmentNo,
		arg.DueDate,
		arg.PrincipalMinor,
		arg.InterestMinor,
		arg.BalanceMinor,
	)
	return err
}

const getLoanByID = `-- name: GetLoanByID :one
SELECT id, customer_id, deposit_account_id, principal_minor, term_months, interest_rate_bps, currency, status, disbursed_at, created_at FROM loans WHERE id = $1
`

func (q *Queries) GetLoanByID(ctx context.Context, id pgtype.UUID) (Loan, error) {
	row := q.db.QueryRow(ctx, getLoanByID, id)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.DepositAccountID,
		&i.PrincipalMinor,
		&i.TermMonths,
		&i.InterestRateBps,
		&i.Currency,
		&i.Status,
		&i.DisbursedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLoanProductByCode = `-- name: GetLoanProductByCode :one
SELECT id, code, name, kind, currency, interest_rate_bps, config, active, created_at FROM product WHERE code = $1 AND kind = 'loan'
`

func (q *Queries) GetLoanProductByCode(ctx context.Context, code string) (Product, error) {
	row := q.db.QueryRow(ctx, getLoanProductByCode, code)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Kind,
		&i.Currency,
		&i.InterestRateBps,
		&i.Config,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listLoanInstallments = `-- name: ListLoanInstallments :many
SELECT id, loan_id, installment_no, due_date, principal_minor, interest_minor, balance_minor, status, paid_at FROM loan_installments WHERE loan_id = $1 ORDER BY installment_no
`

func (q *Queries) ListLoanInstallments(ctx context.Context, loanID pgtype.UUID) ([]LoanInstallment, error) {
	rows, err := q.db.Query(ctx, listLoanInstallments, loanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoanInstallment
	for rows.Next() {
		var i LoanInstallment
		if err := rows.Scan(
			&i.ID,
			&i.LoanID,
			&i.InstallmentNo,
			&i.DueDate,
			&i.PrincipalMinor,
			&i.InterestMinor,
			&i.BalanceMinor,
			&i.Status,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInstallmentPaid = `-- name: MarkInstallmentPaid :exec
UPDATE loan_installments SET status = 'paid', paid_at = now() WHERE id = $1
`

func (q *Queries) MarkInstallmentPaid(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markInstallmentPaid, id)
	return err
}

const nextDueInstallment = `-- name: NextDueInstallment :one
SELECT id, loan_id, installment_no, due_date, principal_minor, interest_minor, balance_minor, status, paid_at FROM loan_installments WHERE loan_id = $1 AND status = 'due' ORDER BY installment_no LIMIT 1
`

func (q *Queries) NextDueInstallment(ctx context.Context, loanID pgtype.UUID) (LoanInstallment, error) {
	row := q.db.QueryRow(ctx, nextDueInstallment, loanID)
	var i LoanInstallment
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.InstallmentNo,
		&i.DueDate,
		&i.PrincipalMinor,
		&i.InterestMinor,
		&i.BalanceMinor,
		&i.Status,
		&i.PaidAt,
	)
	return i, err
}

const updateLoanStatus = `-- name: UpdateLoanStatus :exec
UPDATE loans SET status = $2 WHERE id = $1
`

type UpdateLoanStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateLoanStatus(ctx context.Context, arg UpdateLoanStatusParams) error {
	_, err := q.db.Exec(ctx, updateLoanStatus, arg.ID, arg.Status)
	return err
}
