// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChartOfAccount struct {
	ID       pgtype.UUID
	Code     string
	Name     string
	Type     string
	Currency string
}

type Credential struct {
	CustomerID   pgtype.UUID
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

type Customer struct {
	ID        pgtype.UUID
	Name      string
	Email     string
	Phone     pgtype.Text
	Status    string
	KycStatus string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type JournalEntry struct {
	ID              pgtype.UUID
	TransactionType string
	Description     string
	IdempotencyKey  pgtype.Text
	BookingDate     pgtype.Date
	ValueDate       pgtype.Date
	ReferenceNo     pgtype.Text
	ReversesEntryID pgtype.UUID
	CreatedAt       pgtype.Timestamptz
}

type JournalLine struct {
	ID              pgtype.UUID
	JournalEntryID  pgtype.UUID
	LedgerAccountID pgtype.UUID
	Direction       string
	AmountMinor     int64
	Currency        string
}

type Ping struct {
	ID int32
}
