// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID              pgtype.UUID
	CustomerID      pgtype.UUID
	ProductID       pgtype.UUID
	Currency        string
	Status          string
	LedgerAccountID pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ChartOfAccount struct {
	ID       pgtype.UUID
	Code     string
	Name     string
	Type     string
	Currency string
}

type Credential struct {
	CustomerID   pgtype.UUID
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

type Customer struct {
	ID        pgtype.UUID
	Name      string
	Email     string
	Phone     pgtype.Text
	Status    string
	KycStatus string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Hold struct {
	ID          pgtype.UUID
	AccountID   pgtype.UUID
	AmountMinor int64
	Currency    string
	Status      string
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type IdempotencyKey struct {
	Key          string
	RequestHash  string
	ResponseBody []byte
	StatusCode   int32
	CreatedAt    pgtype.Timestamptz
}

type InterestAccrual struct {
	ID          pgtype.UUID
	AccountID   pgtype.UUID
	AccrualDate pgtype.Date
	AmountMinor int64
	Currency    string
	Capitalized bool
	CreatedAt   pgtype.Timestamptz
}

type JournalEntry struct {
	ID              pgtype.UUID
	TransactionType string
	Description     string
	IdempotencyKey  pgtype.Text
	BookingDate     pgtype.Date
	ValueDate       pgtype.Date
	ReferenceNo     pgtype.Text
	ReversesEntryID pgtype.UUID
	CreatedAt       pgtype.Timestamptz
}

type JournalLine struct {
	ID              pgtype.UUID
	JournalEntryID  pgtype.UUID
	LedgerAccountID pgtype.UUID
	Direction       string
	AmountMinor     int64
	Currency        string
}

type Loan struct {
	ID               pgtype.UUID
	CustomerID       pgtype.UUID
	DepositAccountID pgtype.UUID
	PrincipalMinor   int64
	TermMonths       int32
	InterestRateBps  int32
	Currency         string
	Status           string
	DisbursedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type LoanInstallment struct {
	ID             pgtype.UUID
	LoanID         pgtype.UUID
	InstallmentNo  int32
	DueDate        pgtype.Date
	PrincipalMinor int64
	InterestMinor  int64
	BalanceMinor   int64
	Status         string
	PaidAt         pgtype.Timestamptz
}

type Ping struct {
	ID int32
}

type Product struct {
	ID              pgtype.UUID
	Code            string
	Name            string
	Kind            string
	Currency        string
	InterestRateBps int32
	Config          []byte
	Active          bool
	CreatedAt       pgtype.Timestamptz
}
