// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID        pgtype.UUID
	Name      string
	Email     string
	Phone     pgtype.Text
	Status    string
	KycStatus string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Ping struct {
	ID int32
}
