// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ping.sql

package postgres

import (
	"context"
)

const countPings = `-- name: CountPings :one
SELECT count(*) FROM ping
`

func (q *Queries) CountPings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPings)
	var count int64
	err := row.Scan(&count)
	return count, err
}
