// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reversal.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReversingEntry = `-- name: CreateReversingEntry :one
INSERT INTO journal_entry (transaction_type, description, booking_date, value_date, reverses_entry_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateReversingEntryParams struct {
	TransactionType string
	Description     string
	BookingDate     pgtype.Date
	ValueDate       pgtype.Date
	ReversesEntryID pgtype.UUID
}

func (q *Queries) CreateReversingEntry(ctx context.Context, arg CreateReversingEntryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createReversingEntry,
		arg.TransactionType,
		arg.Description,
		arg.BookingDate,
		arg.ValueDate,
		arg.ReversesEntryID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
