// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statement.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const balanceAsOf = `-- name: BalanceAsOf :one
SELECT COALESCE(SUM(
  CASE WHEN jl.direction = 'credit' THEN jl.amount_minor ELSE -jl.amount_minor END
), 0)::bigint
FROM journal_line jl
JOIN journal_entry je ON je.id = jl.journal_entry_id
WHERE jl.ledger_account_id = $1 AND je.booking_date < $2::date
`

type BalanceAsOfParams struct {
	LedgerAccountID pgtype.UUID
	Before          pgtype.Date
}

func (q *Queries) BalanceAsOf(ctx context.Context, arg BalanceAsOfParams) (int64, error) {
	row := q.db.QueryRow(ctx, balanceAsOf, arg.LedgerAccountID, arg.Before)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const linesInPeriod = `-- name: LinesInPeriod :many
SELECT je.booking_date, je.transaction_type, jl.direction, jl.amount_minor, jl.currency
FROM journal_line jl
JOIN journal_entry je ON je.id = jl.journal_entry_id
WHERE jl.ledger_account_id = $1
  AND je.booking_date >= $2::date
  AND je.booking_date < $3::date
ORDER BY je.booking_date
`

type LinesInPeriodParams struct {
	LedgerAccountID pgtype.UUID
	FromDate        pgtype.Date
	ToDate          pgtype.Date
}

type LinesInPeriodRow struct {
	BookingDate     pgtype.Date
	TransactionType string
	Direction       string
	AmountMinor     int64
	Currency        string
}

func (q *Queries) LinesInPeriod(ctx context.Context, arg LinesInPeriodParams) ([]LinesInPeriodRow, error) {
	rows, err := q.db.Query(ctx, linesInPeriod, arg.LedgerAccountID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinesInPeriodRow
	for rows.Next() {
		var i LinesInPeriodRow
		if err := rows.Scan(
			&i.BookingDate,
			&i.TransactionType,
			&i.Direction,
			&i.AmountMinor,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
